# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.CharField(max_length=5000)),
                ('views', models.IntegerField(default=1)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
